### ISSUE TITLE
module.ecs.data.aws_ecs_task_definition.web: 1 error(s) occurred

### ISSUE THREAD

**Issue by mabushey** [duduribeiro/terraform_ecs_fargate_example#1]
Hello,

It errored on an apply, and now plan/apply gives this:

 aws_route53_record.www-prod: Refreshing state... (ID: Z2BMRACSMJPALR_www.mysite.com_A)

Error: Error refreshing state: 1 error(s) occurred:

* module.ecs.data.aws_ecs_task_definition.web: 1 error(s) occurred:

* module.ecs.data.aws_ecs_task_definition.web: data.aws_ecs_task_definition.web: Failed getting task definition ClientException: Unable to describe task definition.
        status code: 400, request id: f61eb680-293a-11e8-ab3b-0fb5ad391a32 "tutorial_web"

Thanks!

**Comment by mabushey** [comment]
Adding a depends_on in modules/ecs/main.tf appears to have gotten things working:

```
 /* Simply specify the family to find the latest ACTIVE revision in that family */
 data "aws_ecs_task_definition" "web" {
+  depends_on = ["aws_ecs_task_definition.web"]
   task_definition = "${aws_ecs_task_definition.web.family}"
 }
```

**Comment by chikeagu** [comment]
Hi mabushey, 

I've been trying to get this project to work in AWS but have not been able so far. I'm currently stuck at the CodePipeline failing to build an image. 

Were you able to run this project end-to-end without issues?

**Comment by chikeagu** [comment]
I'm not sure if my issues are stemming from the fact that AWS CodePipeline cannot find the repo openjobs_experiment under modules/code_pipeline/main.tf

**Comment by austenito** [comment]
@mabushey fix seems to have resolved the problem :)

**Comment by andrewjkrull** [comment]
So @mabushey this fixed part of my problem. I now am receiving the following errors:

Error: Error applying plan:

2 error(s) occurred:

* module.rds.aws_db_instance.rds: 1 error(s) occurred:

* aws_db_instance.rds: Error creating DB Instance: DBSnapshotNotFound: DBSnapshot not found: rds-production-snapshot
	status code: 404, request id: 547a3b56-28b4-4267-a9ca-eeec98c60000
* module.code_pipeline.aws_s3_bucket.source: 1 error(s) occurred:

* aws_s3_bucket.source: Error creating S3 bucket: AuthorizationHeaderMalformed: The authorization header is malformed; the region 'us-east-1' is wrong; expecting 'eu-west-1'
	status code: 400, request id: 43715315C551FB72, host id: CbbBjqtXPxSXomxr26iSjKrgSiSIMI8ZrtyWb22YCcLDETbfIxCb7QXIZpZ1HcXshSULebjGV2I=

Found a comment in the Medium article for this that someone commented out the snapshot_identifier, I applied that and I am still receiving the following error:

Error: Error applying plan:

1 error(s) occurred:

* module.code_pipeline.aws_s3_bucket.source: 1 error(s) occurred:

* aws_s3_bucket.source: Error creating S3 bucket: AuthorizationHeaderMalformed: The authorization header is malformed; the region 'us-east-1' is wrong; expecting 'eu-west-1'
	status code: 400, request id: 826AC1CDD1E4AE7F, host id: S0sAJO/REWWoTsQbSo1haIg6xlIUjLIr3oPCcWxssu8Em/0Lzdu2gK5bjHer9oBSAshGGYmTjaE=

I don't know how or where eu-west-1 is coming into anything right now.

**Comment by 20k-ultra** [comment]
@Minnow47 You're getting 

> The authorization header is malformed; the region 'us-east-1' is wrong; expecting 'eu-west-1'

 because the repo is using a bucket named "openjobs-experiment-source" in [/modules/code_pipeline/main.tf](https://github.com/duduribeiro/terraform_ecs_fargate_example/blob/master/modules/code_pipeline/main.tf#L2) which most likely is in `eu-west-1` location. If you change this bucket name to something unique across all S3 instances then it will correctly be made.

Thank you for mentioning that commenting out the snapshot fixes the db issue.

@mabushey The depends_on change also fixed my issue with task definition.

**Comment by duduribeiro** [comment]
thanks for answering the issue @mabushey. Adding `depends_on` is a fix for it. I will close this issue.
