### ISSUE TITLE
Error creating DB Instance: DBSnapshotNotFound

### ISSUE THREAD

**Issue by devopsdymyr** [duduribeiro/terraform_ecs_fargate_example#7]
terraform apply issue,please once update source file 
![screenshot from 2019-02-02 13-58-19](https://user-images.githubusercontent.com/41105507/52161971-fd974080-26f2-11e9-8316-35111c50d2b8.png)

**Comment by MartinCerny-awin** [comment]
I have fixed it by commenting snapshot_identifier

> #snapshot_identifier    = "rds-${var.environment}-snapshot"

in modules/rds/output.tf

snapshot_identifier - (Optional) Specifies whether or not to create this database from a snapshot. This correlates to the snapshot ID you'd find in the RDS console, e.g: rds:production-2015-06-26-06-05.
